In [7]:
import numpy as np

# 1. 创建3x4的二维数组（元素1~12）
array = np.arange(1, 13).reshape(3, 4)

# 打印数组的形状、维度和数据类型
print("原始数组：")
print(array)
print(f"形状：{array.shape}")    # 输出：(3, 4)
print(f"维度：{array.ndim}")     # 输出：2
print(f"数据类型：{array.dtype}") # 输出：int32

# 2. 将数组元素乘以2
array_x2 = array * 2
print("\n乘以2后的数组：")
print(array_x2)

# 3. 将数组重塑为4x3的形状
reshaped_array = array.reshape(4, 3)
print("\n重塑为4x3后的数组：")
print(reshaped_array)

原始数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
形状：(3, 4)
维度：2
数据类型：int32

乘以2后的数组：
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为4x3后的数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np

# 给定的4x4数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第2行所有元素（索引为1，因为Python索引从0开始）
row_2 = array[1, :]
print("第2行元素：", row_2)  # 输出：[5 6 7 8]

# 2. 提取第3列所有元素（索引为2）
col_3 = array[:, 2]
print("第3列元素：", col_3)  # 输出：[ 3  7 11 15]

# 3. 提取子数组（第1、2行和第2、3列）
# 行索引0-1，列索引1-2
sub_array = array[0:2, 1:3]
print("子数组：\n", sub_array)  # 输出：[[2 3] [6 7]]

# 4. 将大于10的元素替换为0
mask = array > 10
array[mask] = 0
print("替换后的数组：\n", array)
# 输出：
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10  0  0]
#  [ 0  0  0  0]]

第2行元素： [5 6 7 8]
第3列元素： [ 3  7 11 15]
子数组：
 [[2 3]
 [6 7]]
替换后的数组：
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [5]:
import numpy as np

# 创建数组A（3x2）和数组B（1x2）
A = np.arange(1, 7).reshape(3, 2)
B = np.array([10, 20])

print("数组A：\n", A)
print("数组B：", B)

# 1. 逐元素相加（广播）
sum_result = A + B
print("\nA + B：\n", sum_result)

# 2. 逐元素相乘（广播）
multiply_result = A * B
print("\nA * B：\n", multiply_result)

# 3. 计算A的每一行与B的点积
dot_result = np.sum(A * B, axis=1)
# 或者使用：dot_result = np.dot(A, B)
print("\nA的每行与B的点积：", dot_result)

数组A：
 [[1 2]
 [3 4]
 [5 6]]
数组B： [10 20]

A + B：
 [[11 22]
 [13 24]
 [15 26]]

A * B：
 [[ 10  40]
 [ 30  80]
 [ 50 120]]

A的每行与B的点积： [ 50 110 170]
